# Site settings
title: noroxy's blog
email: toxzcp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  '<a href="http://github.com/noproxy" target="_blank">noproxy</a>'s blog. Mainly about Gradle and Android.'
baseurl: / # the subpath of your site, e.g. /blog/
url: "http://noproxy.netlify.com"
twitter_username: noproxy
github_username:  noproxy

author:
  name:           'noporxy'
  url:            https://twitter.com/mdo

github:
  repo:           https://github.com/poole/hyde

paginate:         5
permalink:        pretty

# Build settings
plugins:
  - jekyll-asciidoc

markdown: kramdown
highlighter: rouge
asciidoc:
  ext: asciidoc,adoc,ad

# Content settings
collections:
  gradle:
    output: true
